import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Safe Analytics component with error handling
const SafeAnalytics = () => {
  if (process.env.NODE_ENV !== "production" || typeof window === "undefined") {
    return null;
  }

  return null; // Skip analytics for now to avoid provider errors
};

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Smart Kid App",
  description: "Generated by Hitha",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full">{children}</body>

      <SafeAnalytics />
    </html>
  );
}
